class Elemen():
    regist_btn = "/html/body/div[4]/div[1]/div[1]/div[2]/div[1]/ul/li[1]/a"
    gender = "gender-male"
    first_name = "FirstName"
    last_name = "LastName"
    email = "Email"
    password = "Password"
    confirm_pw = "ConfirmPassword"
    login_btn = "/html/body/div[4]/div[1]/div[4]/div[2]/div/div[2]/div[1]/div[2]/div[2]/form/div[5]/input"
    gift_card = "/html/body/div[4]/div[1]/div[4]/div[3]/div/div/div[3]/div[2]/div/div[2]/h2/a"
    recipient_name = "giftcard_2_RecipientName"
    recipient_email = "giftcard_2_RecipientEmail"
    btn_cart = "add-to-cart-button-2"
    shopping_cart = "/html/body/div[4]/div[1]/div[1]/div[2]/div[1]/ul/li[3]/a/span[1]"
    checklist_btn = "termsofservice"
    checkout_btn = "checkout"
